config/routes.rb
Connoisseur::Application.routes.draw do
  resources :stores
  resources :products
  root "products#index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	require 'open-uri'

 	def index
 		per_page = params[:per_page] || 20
 		page = params[:page] || 1
		products_json = open("http://lcboapi.com/products?per_page=#{per_page}&page=#{page}").read
    	@products = JSON.parse(products_json)
  	end

  	def show
 		product = open("http://lcboapi.com/products/#{params[:id]}").read
 		json = JSON.parse(product)
 		@product = json['result']
 		inventory = open("http://lcboapi.com/products/#{params[:id]}/inventories").read
 		jpon = JSON.parse(inventory)
 		@inventory = jpon['result']
  	end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index 
  	stores = JSON.parse(open("http://lcboapi.com/stores").read)
    @stores = stores['result']
  end

  def show
  	@store = JSON.parse(open("http://lcboapi.com/stores/#{params[:id]}").read)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def format_price(cents)
  		price_in_dollars = cents.to_f / 100
  		sprintf("$%.2f", price_in_dollars)
  	end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

    <%= javascript_include_tag "application" %>

    <%= params %>
  </body>
</html>

app/views/products/index.html.erb
<div class="row">
	<div class="small-12 columns">
	<div class="text-center"><h1>Booze</h1>
    <h3><%= link_to "Stores", stores_path %></h3></div><br>
		<ul class="small-block-grid-2 large-block-grid-4 text-center">
			<% @products['result'].each do |product| %>
	  			<li><img src="<%= product['image_thumb_url'] %>"><br>
    			<%= link_to product['name'], product_path(product['id']) %><br>
    			<%= format_price product['price_in_cents'] %><br>
    			<%= product['primary_category'] %>
    			</li>
    		<% end %>
    	</ul>
    	<div class="text-center"><h4><%= link_to 'Previous', products_path(:page => @products['pager']['previous_page'])%> | <%= link_to 'Next', products_path(:page => @products['pager']['next_page']) %> </h4></div>
    </div>
</div>

app/views/products/show.html.erb
<div class="row">
	<div class="small-12 columns">
		<div class="text-center">
			<h1><%= @product['name'] %></h1><br>
			<%= image_tag @product['image_thumb_url'] %><br>
    		$<%= format_price @product['price_in_cents'] %><br>
    		<%= @product['description'] %>
    	</div>
	</div>
</div>

app/views/stores/index.html.erb
<div class="row">
<div class="small-12 columns">
<div class="text-center"><h1>Stores</h1>
<h3><%= link_to "Back to Products", products_path %></h3></div><br>
		
<ul class="small-block-grid-2 large-block-grid-4 text-center">
			<% @stores.each do |store| %>
	  			<li><img src="http://www.auroraimporting.com/wp-content/uploads/LCBO-logo-7E6B6267B2-seeklogo_com.gif"><br>
    			<%= link_to store['name'], store_path(store['id']) %><br>
    			<%= store['address_line_1'] %><br>
    			<%= store['address_line_2'] %><br>		
    			<%= store['address_line_2'] %><br>
    			<%= store['address_line_2'] %><br>
    			</li>
    		<% end %>
    	</ul>
    </div>
</div>

app/views/stores/show.html.erb
<div class="row">
	<div class="small-12 columns">
		<div class="text-center">
			<h1><%= @store['name'] %></h1><br>
			<img src="http://www.auroraimporting.com/wp-content/uploads/LCBO-logo-7E6B6267B2-seeklogo_com.gif"><br>
    		<p>Price: <%= format_price @product['price_in_cents'] %><br>
    		Package: <%= @product['package'] %><br>
    		Type: <%= @product['primary_category'] %><br>
    		Category: <%= @product['secondary_category'] %><br>
    		Producer: <%= @product['producer_name'] %><br>
    		Origin: <%= @product['origin'] %><br>
    		LCBO Inventory Count: <%= @product['inventory_count'] %></p>
    	</div>
	</div>
</div>